### ISSUE TITLE
How to set generation sampling parameters?

### ISSUE THREAD

**Issue by rawsh** [huggingface/open-r1#328]
# This is blocking reproducing r1 distilled models on AIME

Need to use deepseek reference settings of temperature=0.6, top_p=0.95. 

Greedy sampling does poorly on AIME:

## r1-1.5B
- AIME24: 23.33%

Tried to refer to lighteval docs and ran into issues using model config:
```
model: # Model specific parameters
  base_params:
    model_args: "pretrained=Qwen/Qwen2.5-7B-Instruct,dtype=bfloat16,max_model_length=768,gpu_memory_utilisation=0.7" # Model args that you would pass in the command line
  generation: # Generation specific parameters
    temperature: 1.0
    stop_tokens: null
    truncate_prompt: false
```

run with:
```
TASK=aime24 lighteval vllm \
    "config.yaml" \
    "custom|$TASK|0|0" \
    --custom-tasks tasks.py \
    --use-chat-template \
    --output-dir ./results/
```

hitting:
```
TypeError: expected str, bytes or os.PathLike object, not dict
```

[ref](https://github.com/huggingface/lighteval/issues/563)
