### ISSUE TITLE
in SFT script, distributed training got stuck if set `packing=false`

### ISSUE THREAD

**Issue by ChenDRAG** [huggingface/open-r1#343]
I tried to follow the exact README setup for SFT experiments. However, I find that if setting packing = false . Then the process will get stuck at the beginning of the training.

<img width="1209" alt="Image" src="https://github.com/user-attachments/assets/f1a0dd0b-0ab0-4d2f-b53b-575d9a1615d2" />

This is ok in a single GPU setting. SO I assume it must be correlated with NCCL communication

Any ideas why this happens?

**Comment by ChenDRAG** [comment]
Also if  set `per_device_train_batch_size=1` would get this error
```


wandb: ⭐️ View project at https://wandb.ai/noteam2235/huggingface
wandb: 🚀 View run at https://wandb.ai/noteam2235/huggingface/runs/b11ld1bd
  0%|                                                                                                                                               | 0/9 [00:00<?, ?it/s]W0217 07:42:20.851000 470998 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 471406 closing signal SIGTERM
W0217 07:42:20.852000 470998 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 471407 closing signal SIGTERM
W0217 07:42:20.852000 470998 torch/distributed/elastic/multiprocessing/api.py:897] Sending process 471408 closing signal SIGTERM
E0217 07:42:21.080000 470998 torch/distributed/elastic/multiprocessing/api.py:869] failed (exitcode: -9) local_rank: 3 (pid: 471409) of binary: /usr/bin/python
Traceback (most recent call last):
  File "/usr/local/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/accelerate_cli.py", line 48, in main
    args.func(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 1157, in launch_command
    deepspeed_launcher(args)
  File "/usr/local/lib/python3.10/dist-packages/accelerate/commands/launch.py", line 845, in deepspeed_launcher
    distrib_run.run(args)
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/run.py", line 910, in run
    elastic_launch(
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/usr/local/lib/python3.10/dist-packages/torch/distributed/launcher/api.py", line 269, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
```

**Comment by jyC23333** [comment]
I found that if `packing = false` is set, the trl will run this function here:
https://github.com/huggingface/trl/blob/main/trl/trainer/sft_trainer.py#L445
```python
             if packing:
                if args.max_length is None:
                    raise ValueError("When packing is enabled, `max_length` can't be `None`.")
                if isinstance(dataset, Dataset):  # `IterableDataset.map` does not support `desc`
                    map_kwargs["desc"] = f"Packing {dataset_name} dataset"
                dataset = dataset.select_columns("input_ids")
                dataset = dataset.map(
                    pack_examples, batched=True, fn_kwargs={"seq_length": args.max_length}, **map_kwargs
                )
            elif args.max_length is not None:
                dataset = dataset.map(
                    lambda ex: {key: ex[key][: args.max_length] for key in ["input_ids", "attention_mask"]},
                    **map_kwargs,
                )
```
This function process the `input_ids` without thinking about all items in a training batch should have the same context length, and this maybe the reason why training gets stuck using zero3.

I simply change the function as this: 
```python
            elif args.max_seq_length is not None:
                def cut_or_pad(example):
                    if len(example["input_ids"]) >= args.max_seq_length:
                        example["input_ids"] = example["input_ids"][:args.max_seq_length]
                        example["attention_mask"] = example["attention_mask"][:args.max_seq_length]
                    else:
                        pad_lenth = args.max_seq_length - len(example["input_ids"])
                        example["input_ids"] = example["input_ids"] + [processing_class.pad_token_id]*pad_lenth
                        example["attention_mask"] = example["attention_mask"] + [1]*pad_lenth
                    return example
                
                if isinstance(dataset, Dataset):  # `IterableDataset.map` does not support `desc`
                    map_kwargs["desc"] = f"cut_or_pad {dataset_name} dataset"
                dataset = dataset.map(cut_or_pad, **map_kwargs)
```
The training task run correctly.

I think this is a bug because the packing argument shouldn't be set to True during SFT. @lewtun

**Comment by xwy-bit** [comment]
> I found that if `packing = false` is set, the trl will run this function here: https://github.com/huggingface/trl/blob/main/trl/trainer/sft_trainer.py#L445
> 
>              if packing:
>                 if args.max_length is None:
>                     raise ValueError("When packing is enabled, `max_length` can't be `None`.")
>                 if isinstance(dataset, Dataset):  # `IterableDataset.map` does not support `desc`
>                     map_kwargs["desc"] = f"Packing {dataset_name} dataset"
>                 dataset = dataset.select_columns("input_ids")
>                 dataset = dataset.map(
>                     pack_examples, batched=True, fn_kwargs={"seq_length": args.max_length}, **map_kwargs
>                 )
>             elif args.max_length is not None:
>                 dataset = dataset.map(
>                     lambda ex: {key: ex[key][: args.max_length] for key in ["input_ids", "attention_mask"]},
>                     **map_kwargs,
>                 )
> This function process the `input_ids` without thinking about all items in a training batch should have the same context length, and this maybe the reason why training gets stuck using zero3.
> 
> I simply change the function as this:
> 
>             elif args.max_seq_length is not None:
>                 def cut_or_pad(example):
>                     if len(example["input_ids"]) >= args.max_seq_length:
>                         example["input_ids"] = example["input_ids"][:args.max_seq_length]
>                         example["attention_mask"] = example["attention_mask"][:args.max_seq_length]
>                     else:
>                         pad_lenth = args.max_seq_length - len(example["input_ids"])
>                         example["input_ids"] = example["input_ids"] + [processing_class.pad_token_id]*pad_lenth
>                         example["attention_mask"] = example["attention_mask"] + [1]*pad_lenth
>                     return example
>                 
>                 if isinstance(dataset, Dataset):  # `IterableDataset.map` does not support `desc`
>                     map_kwargs["desc"] = f"cut_or_pad {dataset_name} dataset"
>                 dataset = dataset.map(cut_or_pad, **map_kwargs)
> The training task run correctly.
> 
> I think this is a bug because the packing argument shouldn't be set to True during SFT. And the `label` of SFT training should be something related to the chat template, but I didn't find trl processed the `label` in `SFTTrainer`. Maybe I missed something? [@lewtun](https://github.com/lewtun) [@qgallouedec](https://github.com/qgallouedec)

 Same question. After debugging, I found an issue with the label settings during SFT training: only a few tokens like <im_end> are set to -100, while others, such as queries and tokens from other sessions, are also involved in loss calculation, which is quite strange.

**Comment by qgallouedec** [comment]
> about all items in a training batch should have the same context length, 

padding is done by the collator

> I didn't find trl processed the label in SFTTrainer. Maybe I missed something?

labels are equals to input_ids in SFT

Can someone provide the steps to reproduce the "in SFT script, distributed training got stuck if set packing=false"
This works fine with 4 GPUs:

```from trl import SFTConfig, SFTTrainer
from datasets import load_dataset

dataset = load_dataset("trl-lib/Capybara", split="train")

training_args = SFTConfig(output_dir="Qwen/Qwen2.5-0.5B-SFT")
trainer = SFTTrainer(
    args=training_args,
    model="Qwen/Qwen2.5-0.5B",
    train_dataset=dataset,
)
trainer.train()
```

**Comment by jyC23333** [comment]
Thanks so much. @qgallouedec 


> labels are equals to input_ids in SFT

I wonder if this is by design or if this is a bug？This seems to be a quite different way to set `labels`.

---
> Can someone provide the steps to reproduce the "in SFT script, distributed training got stuck if set packing=false"

With 8xA100s, I run the script like this:
```shell
ACCELERATE_LOG_LEVEL=info accelerate launch --config_file recipes/accelerate_configs/zero3.yaml \                                                                         
              src/open_r1/sft.py \           
              --config recipes/Qwen2.5-1.5B-Instruct/sft/config_demo.yaml
```
and the traing config is:
```yaml
# Model arguments
model_name_or_path: ./MODEL/QWEN/Qwen2.5-1.5B-Instruct
model_revision: main
torch_dtype: bfloat16
attn_implementation: flash_attention_2

# Data training arguments
dataset_name: ./hf_cache/datasets/hf-Bespoke-Stratos-17k
dataset_configs:
- all
preprocessing_num_workers: 8

# SFT trainer config
bf16: true
do_eval: true
eval_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen2.5-1.5B-Open-R1-Distill
hub_strategy: every_save
learning_rate: 2.0e-05
log_level: info
logging_steps: 1
logging_strategy: steps
lr_scheduler_type: cosine
packing: false
max_seq_length: 4096
max_steps: -1
num_train_epochs: 1
output_dir: ./results/Qwen2.5-1.5B-Open-R1-Distill-nopack
overwrite_output_dir: true
per_device_eval_batch_size: 2
per_device_train_batch_size: 2
push_to_hub: false
report_to:
- wandb
save_strategy: "no"
seed: 42
warmup_ratio: 0.1
```
only `packing=false` is set. And the `hf-Bespoke-Stratos-17k` dataset is downloaded from [here](https://huggingface.co/datasets/HuggingFaceH4/Bespoke-Stratos-17k).

By the way, I'm using CUDA12.2. Maybe this is a main reason to cause stuck? But this version runs correctly when `packing=true` or grpo training.

**Comment by HwangYej1** [comment]
have you solved this problem and reproduced distilled results in AIME and Math-500?

**Comment by winterdrive** [comment]
I also encountered a similar problem when using multi-GPU for SFT with `SFTTrainer`.

**Here's what I found:**

* **Successful Scenario:** Distributed training with multiple GPUs works fine when the `packing` argument is **removed** from the `SFTConfig`.
* **Problematic Scenarios:** Setting `packing=true` or `packing=false` both lead to training getting stuck in my case, similar to what you described for `packing=false`.

**My setup and command in Successful Scenario (without `packing`):**

- command:
```bash
accelerate launch   --config_file recipes/accelerate_configs/8v100.yaml   --num_processes 8   --main_process_port 29500   --machine_rank 0   --mixed_precision fp16   src/open_r1/sft.py   --model_name_or_path Qwen/Qwen2.5-7B-Instruct   --dataset_name open-r1/OpenR1-Math-220k   --learning_rate 0.00002   --num_train_epochs 1   --max_seq_length 2048   --per_device_train_batch_size 2   --gradient_accumulation_steps 4   --gradient_checkpointing   --fp16   --output_dir data/Qwen2.5-7B-Open-R1-Distill-0317   --log_level info   --dataloader_num_workers 4
```

- setup: Config file (8v100.yaml)
```yaml
compute_environment: LOCAL_MACHINE
debug: false
deepspeed_config:
  deepspeed_multinode_launcher: standard
  offload_optimizer_device: cpu
  offload_param_device: cpu
  zero_stage: 2
distributed_type: DEEPSPEED
downcast_bf16: 'no'
machine_rank: 0
main_training_function: main
mixed_precision: fp16
num_machines: 1
num_processes: 8
rdzv_backend: static
same_network: true
tpu_env: []
tpu_use_cluster: false
tpu_use_sudo: false
use_cpu: false
```

**Example Error Log (when `packing=false` is set):**

```
rank0: Traceback (most recent call last):
rank0:   File "/home/ubuntu/OpenR1_PT/open-r1/src/open_r1/sft.py", line 198, in <module>
rank0:     main(script_args, training_args, model_args)
... (traceback) ...
rank0: torch.distributed.DistBackendError: NCCL error in: ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:2251, internal error - please report this issue to the NCCL developers, NCCL version 2.21.5
rank0: ncclInternalError: Internal check failed.
rank0: Last error:
rank0: Bootstrap : no socket interface found
[2025-03-12 15:49:25,355] [INFO] [config.py:733:init] Config mesh_device None world_size = 8
rank0:[W312 15:49:25.271885311 ProcessGroupNCCL.cpp:1250] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL.
... (warning log) ...
E0312 15:49:26.660000 1078030 torch
```

**Possible Cause:**

It seems the issue might be related to how `packing` interacts with distributed training, potentially with DeepSpeed. The NCCL error in my failed attempt (with `packing=true` or `packing=false`) suggests a communication problem during distributed initialization, which could be triggered by the data packing process.

**Workaround:**

For now, a working workaround for multi-GPU SFT training seems to be **simply removing the `packing` argument** from `SFTConfig` in distributed setups.
