### ISSUE TITLE
[SFT] Model trainned on  Bespoke-Stratos-17k get really low performence on Math-500

### ISSUE THREAD

**Issue by ListentoMe0112** [huggingface/open-r1#396]
I'm new to llm and I'm confused by this. When I'm trainning, my loss value is decreased as expected. But at last my performance is really bad.

## Performance
<img width="510" alt="Image" src="https://github.com/user-attachments/assets/a017845a-972b-4cd9-897d-7753087319a4" />

## Device
My devices are two v100 which is not support bf16. 

## Command
This is my start trainning command
```bash
nohup accelerate launch --config_file recipes/accelerate_configs/zero3.yaml src/open_r1/sft.py --config recipes/Qwen2.5-1.5B-Instruct/sft/config_demo.yaml > train.log 2>&1 &
```

## Config
This is my config_demo.yaml

```yaml
# Model arguments
model_name_or_path: Qwen/Qwen2.5-1.5B-Instruct
model_revision: main
torch_dtype: float16
# attn_implementation: flash_attention_2

# Data training arguments
dataset_name: HuggingFaceH4/Bespoke-Stratos-17k
dataset_configs:
- all
preprocessing_num_workers: 2

# SFT trainer config
bf16: true
do_eval: true
eval_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 1
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: Qwen2.5-1.5B-Open-R1-Distill
hub_strategy: every_save
learning_rate: 2.0e-05
log_level: info
logging_steps: 5
logging_strategy: steps
lr_scheduler_type: cosine
packing: true
max_seq_length: 2048
max_steps: -1
num_train_epochs: 1
output_dir: data/Qwen2.5-1.5B-Open-R1-Distill
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 1
push_to_hub: true
report_to:
- wandb
save_strategy: "no"
seed: 42
warmup_ratio: 0.1
```
## Model Card 
https://huggingface.co/yeeboxie/Qwen2.5-1.5B-Open-R1-Distill/blob/main/README.md

## Trainning Log
https://wandb.ai/1904087817-tencent/huggingface/runs/0nnfxwdj

Any help would be appreciated!
