### ISSUE TITLE
Proposal: extensible reward functions

### ISSUE THREAD

**Issue by esnible** [huggingface/open-r1#547]
Open R1 includes a Reward Functions Registry with 11 rewards.  There is no way to add new reward functions without creating a custom version of Open R1.

**Describe the solution you'd like**
Provide a way for experiment configuration to specify the installation and invocation of new reward functions.

Typically a developer creates a reward function and wishes to test it by supplying it to a pod or VM running Open R1.  I'd like the developer to be able to supply reward functions
- By supplying the code through volume mounts
- By supplying the code through GitHub or PyPI

I'd like the experimenter to be able to configure Open R1 to use custom functions through a reward-function `python_package` which loads and invokes a Python reward function that is not built into R1.  For example:

```yaml
reward_funcs:
  - python_package:
       # Reward function already mounted in Open R1 pod
       package: /mymount/mycode
       pip_args: --editable
       python_module: haiku.haiku
       python_function: haiku_reward
```

```yaml
reward_funcs:
  - python_package:
       # Reward function to be fetched from GitHub
       package: git+https://github.com/esnible/test-reward-repo.git
       python_module: haiku.haiku
       python_function: haiku_reward
```

For example, here is a custom (humorous, untested) Python reward function to prefer completions that have 17 syllables, in the style of a Japanese Haiku poem:

```Python
import syllables

def haiku_reward(completions: list[list[Dict[str, str]]], **kwargs) -> float:
   """
   Reward the completion with the closest number of syllables to 17.

   This simulates a reward that promotes the solution that is closest to a Haiku poem.
   """

   # Get the 'content' field of the first completion
   contents = [completion[0]["content"] for completion in completions]

   # Calculate the reward for all completions
   return [-abs(17 - syllables.estimate(content)) for content in contents]
```

A developer would write this code and ad a small _setup.py_.  They next mount it to their Open R1 system, or push it to GitHub or PyPI.  Then they would use it to run experiments.

The implementation of a reward function loader for this new type in R1 should be very simple, probably something similar to

```Python
   if package_name:
      pip._internal.main(['install’, pip_args, package_name])

   mod = importlib.import_module(module_name)
   return getattr(mod, python_function)
```

**Security**
My thought is that security can be ignored -- anyone who can create an experiment probably has permission to mount or download custom code.
If security is an issue an environment variable can be introduced that disables the `python_package` reward function so that Open R1 admins/deployers who don't want their users to bring in custom reward functions will not have the ability.

**If there is interest in this Issue, I will be able to implement it and offer it as a PR.**
